### PR TITLE
added ability to setup multiple vmagents

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
added ability to setup multiple VMagent instances with different configurations

### CODE REVIEW

**Review by zekker6 — COMMENTED** [review]
@AndrewChubatiuk Could you please elaborate on the changes in this PR?
It would be great to see the use-case for the updates and how to use an updated version.

My concern is that this PR introduces a set of changes:
- removing alertmanager in favor of vmalert's `-notifier.blackhole` - could you extract this to a separate PR?
- adding an ability to configure custom repository for VM compoentns to be used - could you move this to a separate PR as well? Also, it seems like current implementation only allows changing registry and organization. Maybe it is better to override full name instead? (similar to what we do for charts - https://github.com/VictoriaMetrics/helm-charts/blob/aad26d596ed88e0bfbbe5b05a491b6e149e8b4b6/charts/victoria-metrics-single/values.yaml#L39-L43) 
- updating chart format to support specifying multiple configs for vmagent and vmsingle used in testing

As far as I understand(please correct me if I've missed something here) the last change allows specifying multiple vmagent and vmsingle configurations. Each configuration will use `.Values.vmagent` and `.Values.vmsingle` values by default.
Can the same be achieved by creating several deployments of this chart with different `values`?

**Comment by AndrewChubatiuk** [comment]
with multiple deployments of a chart you do not necessary need both vmsingle and vmagent, well it can be solved with adding flags like `vmagent.enabled` or `vmsingle.enabled`, but main idea of ability to spin up multiple agents using one helm chart deployment is ability to have common config and override only things, that differ (image), especially taking in account, that it makes sense to use it to compare performance difference before and after done optimization, so setups may have similar configs

**Comment by zekker6** [comment]
This use-case seems to be a bit different from the idea of this chart - to provide an ability to run benchmark on any Prometheus-compatible remote write targets.
Because of this I would suggest adding flags to disabled vmagent/vmsingle deployments and using multiple values files/deployments to achieve the same with fewer changes in chart. For example:
- `values-vmagent-v1.yaml`:
  ```
  vm:
    image:
      tag: testing-v1
  
  vmsingle:
    enabled: false
  ```
- `values-vmagent-v2.yaml`:
  ```
  vm:
    image:
      tag: testing-v2
  
  vmsingle:
    enabled: false
  ```
- `values-common.yaml`:
  ```
  # all common parameters for benchmark
  
  remoteStorages:
    vm:
      writeURL: "http://victoria-metrics-victoria-metrics-cluster-vminsert.default.svc.cluster.local:8480/insert/0/prometheus/api/v1/write"
  ```

And just use multiple values to create deployments:
- `helm install --values values-common.yaml --values values-vmagent-v1.yaml ./`
- `helm install --values values-common.yaml --values values-vmagent-v2.yaml ./`

**Comment by AndrewChubatiuk** [comment]
don't like this idea, just closing

**Pull request closed without merging**
